/** Add-ons shown on the AI logo completed page after a concept is selected. */
export const LOGO_CREATOR_ADDONS = [
  {
    id: 'business-cards',
    title: 'Business Cards',
    price: 75,
    compareAt: 100,
    template: '/assets/images/mockups/mockup-business-card.jpg',
    kind: 'business-card',
    slot: { x: 0.185, y: 0.228, w: 0.63, h: 0.542 },
  },
  {
    id: 'tshirt-design',
    title: 'T-shirt Design',
    price: 85,
    compareAt: 120,
    template: '/assets/images/mockups/mockup-tshirt.jpg',
    kind: 'logo-slot',
    slot: { x: 0.33, y: 0.22, w: 0.34, h: 0.34 },
  },
  {
    id: 'stickers',
    title: 'Stickers',
    price: 65,
    compareAt: 90,
    template: '/assets/images/mockups/mockup-stickers.jpg',
    kind: 'stickers',
    circles: [
      { cx: 0.288, cy: 0.342, r: 0.218 },
      { cx: 0.712, cy: 0.577, r: 0.238 },
      { cx: 0.369, cy: 0.777, r: 0.134 },
    ],
  },
  {
    id: 'door-hangers',
    title: 'Door Hangers',
    price: 75,
    compareAt: 100,
    template: '/assets/images/mockups/mockup-door-hanger.jpg',
    kind: 'logo-slot',
    slot: { x: 0.365, y: 0.425, w: 0.23, h: 0.29 },
  },
  {
    id: 'caps',
    title: 'Caps',
    price: 85,
    compareAt: 120,
    template: '/assets/images/mockups/mockup-cap.jpg',
    kind: 'logo-slot',
    slot: { x: 0.32, y: 0.26, w: 0.28, h: 0.24, rotate: 8 },
  },
  {
    id: 'retractable-banners',
    title: 'Retractable Banners',
    price: 125,
    compareAt: 175,
    template: '/assets/images/mockups/mockup-retractable-banner.jpg',
    kind: 'logo-slot',
    slot: { x: 0.34, y: 0.18, w: 0.32, h: 0.44 },
  },
];
